### ISSUE TITLE
用Linux服务器上安装此插件只能安装0.22版本

### ISSUE THREAD

**Issue by phtty** [BigOrangeQWQ/nonebot_plugin_orangedice#15]
如何在Linux上安装最新的0.35版本呢

**Comment by BigOrangeQWQ** [comment]
尝试使用指令
pip install nonebot-plugin-orangedice==0.3.5
如果无法安装请提供一下log
理应来说python包是与系统无关的

**Comment by BigOrangeQWQ** [comment]
询问了一下别人，我建议你使用pypi本身的源进行安装，不要使用其他镜像源，第三方源会导致包的依赖安装 sqlmodel 出现问题。

**Comment by phtty** [comment]
> 

问题找到了，因为服务器使用Ubuntu20.2LTS系统，默认python是3.8，0.35版本提示需要python3.9，我之前是在本地windows环境进行测试的，本地环境安装了最新版python
