### ISSUE TITLE
关于logs单字符换行保存的疑问

### ISSUE THREAD

**Issue by RomuuuJP** [BigOrangeQWQ/nonebot_plugin_orangedice#24]
感谢您的项目
我目前在以您的项目为基底，用自己超低的技术力修改功能以满足自己的需求并搭建私骰。
目前有一项比较困扰的事情想要咨询您，我注意到logs导出是以单字符换行的形式存储的txt文档。
请问这种设计是为了适配什么功能还是有其他用意呢？
btw 我是coc跑团新手，很多东西都是咨询kp朋友的。但是对于log他也不常用所以不了解。

如果您能解答那将非常有帮助。
再次感谢您的项目。
期待您的回复。

**Comment by BigOrangeQWQ** [comment]
很感谢这个问题的提出。

实际上 logs 的导出最佳结构应该是一个 Object。

即储存有用户账号，用户昵称，发言时间，用户发言，是否为旁观者，这五个字段的对象相对较有利后续的真正导出。

**至于现状为什么是txt，因为这个插件弄出来之后那群跑团的把我鸽了，导致我无法从跑团的体验中持续改进此插件。**

**Comment by RomuuuJP** [comment]
非常感谢解答！

您的logs结构对我非常非常有启发。

再次感谢您的项目！
