### ISSUE TITLE
`Self` type 是 `Python3.11` 新特性

### ISSUE THREAD

**Issue by shoucandanghehe** [BigOrangeQWQ/nonebot_plugin_orangedice#8]
https://peps.python.org/pep-0673/
https://docs.python.org/3/library/typing.html#typing.Self
https://github.com/BigOrangeQWQ/nonebot_plugin_orangedice/blob/717ee564412cd8d37980835871c3c371e8224baf/nonebot_plugin_orangedice/utils.py#L2-L30
可以考虑重写一下👆这里
或者声明依赖>=3.11👇
https://github.com/BigOrangeQWQ/nonebot_plugin_orangedice/blob/717ee564412cd8d37980835871c3c371e8224baf/pyproject.toml#L16

**Comment by BigOrangeQWQ** [comment]
稍后修改此部分代码
考虑删除此typing hint
或引入typing extension进行标注

**Comment by BigOrangeQWQ** [comment]
已发版并修正，引入了typing_extensions中的`Self`标注
